### ISSUE TITLE
Access to page via login/pass 

### ISSUE THREAD

**Issue by mtaobiz** [ryanlelek/Raneto#112]
How to make view access some pages or categories only for users have authorization?
For example, access to Editor's manual.
Thanks

**Comment by mtaobiz** [comment]
Second question: how to set few users in config?
Now i have only 1 user:
```
credentials    : {
    username : 'admin',
    password : 'password'
  }, 
```

**Comment by ryanlelek** [comment]
Right now:
- login is either all or nothing and not set per page.
- multiple users are not currently supported (I opened #114 for this request)

Marking as up for grabs

**Comment by mtaobiz** [comment]
Thank you!
How protect all pages by login/pass?

**Comment by tommysch** [comment]
@mtaobiz you can add authentication to the layout.html begore the <!DOCTYPE html> add

{{#config.authentication}}
{{#loggedIn}}

and in the end of the document add

{{/loggedIn}}
{{/config.authentication}}

**Comment by ryanlelek** [comment]
Thanks @tommysch, that's a good solution.
Does that work for you @mtaobiz ?

**Comment by ryanlelek** [comment]
@mohammadrafigh progressed this ticket with his PR #129

**Comment by fbo** [comment]
I think good with a specific ACL, sample:
{{#config.auth.bygroup}} 

and it possible add LDAP authentification support ?:
https://www.ibm.com/developerworks/library/se-use-ldap-authentication-authorization-node.js-bluemix-application/
https://github.com/vesse/passport-ldapauth

**Comment by ryanlelek** [comment]
Including this in the Roadmap for v0.19 as a "Nice to Have" (link above this comment)
Please join the discussion there or re-open the issue

LDAP is likely out of scope for a while @fbo 
If you still want it, please submit a separate issue with details on how you'd like the LDAP permissions to work
