### ISSUE TITLE
Is it possible to integrate with another Nodejs app or Sails.js app

### ISSUE THREAD

**Issue by amuntasim** [ryanlelek/Raneto#118]
Something like mounting in some path.
example.com/kb

**Comment by ryanlelek** [comment]
There isn't a way currently, but I see how that would be useful.

Some files/ideas on how to integrate:
- all the routes in `app.js` (app.get, app.post) could have a "mount path"
- the mount path will default to "/" in the configuration files

**Comment by dam1** [comment]
Yes, in example/server.js :

 remove
`var server = app.listen(app.get('port'), function () { 
`

exports the app
`exports.app = raneto(config);
`

In your node app
```
	var raneto = require('./example/server').app;
	app.use('/help/', raneto);
```

You will also need to install the missing dependencies manually.

**Comment by ryanlelek** [comment]
Thank you for the info @dam1 

I'll add this to the documentation update megathread.
We're moving to a separate repo for the example.
This is similar to your use-case so let's add it to the docs

Sails would be out of scope for now
Closing this, please continue discussion in megathread or re-open with further questions
