### ISSUE TITLE
Cannot read property 'excerpt' of null when searching article

### ISSUE THREAD

**Issue by nk-gears** [ryanlelek/Raneto#127]
I am getting a page when i search some article

![error_excerpt](https://cloud.githubusercontent.com/assets/897323/16186594/feca01b0-36e8-11e6-930a-a077ca7e99b6.png)

**Comment by nirmalkumarv** [comment]
It worked based on the fix details mentioned here.

https://github.com/gilbitron/Raneto/issues/107

**Comment by ryanlelek** [comment]
Thanks for reporting and letting us know a fix.
I'll close this issue but add #107 to the Roadmap

Duplicate of #107
