### ISSUE TITLE
error Linux 4.4.16-1-pve

### ISSUE THREAD

**Issue by AndrinS** [ryanlelek/Raneto#145]
Can't install on Proxmox lxc (Ubuntu 16.04)

```
apt-get  install nodejs
apt-get install npm
git clone https://github.com/gilbitron/Raneto.git && cd Raneto && npm install && npm start
```

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'bugs', 'raneto' ]
> 2 info using npm@3.5.2
> 3 info using node@v4.2.6
> 4 silly fetchPackageMetaData raneto
> 5 silly fetchNamedPackageData raneto
> 6 silly mapToRegistry name raneto
> 7 silly mapToRegistry using default registry
> 8 silly mapToRegistry registry https://registry.npmjs.org/
> 9 silly mapToRegistry uri https://registry.npmjs.org/raneto
> 10 verbose request uri https://registry.npmjs.org/raneto
> 11 verbose request no auth needed
> 12 info attempt registry request try #1 at 11:16:53 AM
> 13 verbose request id 49ec22d8da8bb84a
> 14 http request GET https://registry.npmjs.org/raneto
> 15 http 200 https://registry.npmjs.org/raneto
> 16 verbose headers { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
> 16 verbose headers   etag: '"5JEKJZKINTNY07L9GOAR6AU5V"',
> 16 verbose headers   'content-type': 'application/json',
> 16 verbose headers   'content-encoding': 'gzip',
> 16 verbose headers   'cache-control': 'max-age=300',
> 16 verbose headers   'content-length': '3433',
> 16 verbose headers   'accept-ranges': 'bytes',
> 16 verbose headers   date: 'Mon, 12 Sep 2016 09:16:53 GMT',
> 16 verbose headers   via: '1.1 varnish',
> 16 verbose headers   age: '0',
> 16 verbose headers   connection: 'keep-alive',
> 16 verbose headers   'x-served-by': 'cache-ams4421-AMS',
> 16 verbose headers   'x-cache': 'MISS',
> 16 verbose headers   'x-cache-hits': '0',
> 16 verbose headers   'x-timer': 'S1473671813.186247,VS0,VE697',
> 16 verbose headers   vary: 'Accept-Encoding' }
> 17 silly get cb [ 200,
> 17 silly get   { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
> 17 silly get     etag: '"5JEKJZKINTNY07L9GOAR6AU5V"',
> 17 silly get     'content-type': 'application/json',
> 17 silly get     'content-encoding': 'gzip',
> 17 silly get     'cache-control': 'max-age=300',
> 17 silly get     'content-length': '3433',
> 17 silly get     'accept-ranges': 'bytes',
> 17 silly get     date: 'Mon, 12 Sep 2016 09:16:53 GMT',
> 17 silly get     via: '1.1 varnish',
> 17 silly get     age: '0',
> 17 silly get     connection: 'keep-alive',
> 17 silly get     'x-served-by': 'cache-ams4421-AMS',
> 17 silly get     'x-cache': 'MISS',
> 17 silly get     'x-cache-hits': '0',
> 17 silly get     'x-timer': 'S1473671813.186247,VS0,VE697',
> 17 silly get     vary: 'Accept-Encoding' } ]
> 18 verbose get saving raneto to /root/.npm/registry.npmjs.org/raneto/.cache.json
> 19 silly bugs url https://github.com/gilbitron/Raneto/issues
> 20 verbose stack Error: Command failed: xdg-open https://github.com/gilbitron/Raneto/issues
> 20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: www-browser: not found
> 20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: links2: not found
> 20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: elinks: not found
> 20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: links: not found
> 20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: lynx: not found
> 20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: w3m: not found
> 20 verbose stack xdg-open: no method available for opening 'https://github.com/gilbitron/Raneto/issues'
> 20 verbose stack
> 20 verbose stack     at ChildProcess.exithandler (child_process.js:213:12)
> 20 verbose stack     at emitTwo (events.js:87:13)
> 20 verbose stack     at ChildProcess.emit (events.js:172:7)
> 20 verbose stack     at maybeClose (internal/child_process.js:821:16)
> 20 verbose stack     at Socket.<anonymous> (internal/child_process.js:319:11)
> 20 verbose stack     at emitOne (events.js:77:13)
> 20 verbose stack     at Socket.emit (events.js:169:7)
> 20 verbose stack     at Pipe._onclose (net.js:469:12)
> 21 verbose cwd /var/www/raneto/Raneto
> 22 error Linux 4.4.16-1-pve
> 23 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "raneto"
> 24 error node v4.2.6
> 25 error npm  v3.5.2
> 26 error code 3
> 27 error Command failed: xdg-open https://github.com/gilbitron/Raneto/issues
> 27 error /usr/bin/xdg-open: 771: /usr/bin/xdg-open: www-browser: not found
> 27 error /usr/bin/xdg-open: 771: /usr/bin/xdg-open: links2: not found
> 27 error /usr/bin/xdg-open: 771: /usr/bin/xdg-open: elinks: not found
> 27 error /usr/bin/xdg-open: 771: /usr/bin/xdg-open: links: not found
> 27 error /usr/bin/xdg-open: 771: /usr/bin/xdg-open: lynx: not found
> 27 error /usr/bin/xdg-open: 771: /usr/bin/xdg-open: w3m: not found
> 27 error xdg-open: no method available for opening 'https://github.com/gilbitron/Raneto/issues'
> 28 error If you need help, you may report this error at:
> 28 error     https://github.com/npm/npm/issues
> 29 verbose exit [ 1, true ]

**Comment by ryanlelek** [comment]
Please add full command(s) used

**Comment by AndrinS** [comment]
Updated

**Comment by ryanlelek** [comment]
Disclaimer! I have no idea, this is purely a guess.

```
18 verbose get saving raneto to /root/.npm/registry.npmjs.org/raneto/.cache.json
19 silly bugs url https://github.com/gilbitron/Raneto/issues
20 verbose stack Error: Command failed: xdg-open https://github.com/gilbitron/Raneto/issues
20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: www-browser: not found
20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: links2: not found
20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: elinks: not found
20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: links: not found
20 verbose stack /usr/bin/xdg-open: 771: /usr/bin/xdg-open: lynx: not found
```

From those lines, here's my guess.
- For some reason, it may not be able to access the cache save directory `/root/.npm...`
- This could be because it's a directory owned by root, but LXC is running as some non-privileged user (as it should be)
-  you may try `npm_config_cache=/another-dir` to resolve this, before the command (it's an environment variable) or in a different directory with correct permissions

xdg comes in because it detects an issue and tries to be helpful by opening the default web browser, which you have none (on a server probably)

That's about all I know for now

**Comment by ryanlelek** [comment]
Keep in mind that `npm_config_cache=/another-dir` is an example.
If you used that as-is, you'd try to be accessing a root-level directory that probably does not exist

**Comment by AndrinS** [comment]
I changed it to npm_config_cache=/var/npm , still same error.


Am 14.09.2016 um 23:36 schrieb Ryan Lelek:

**Comment by ryanlelek** [comment]
Closing this due to age.
If you're still seeing this in the latest ProxMox, let me know. I'll add it to the roadmap
