### ISSUE TITLE
Acronyms within filenames

### ISSUE THREAD

**Issue by BenGoodmanUK** [ryanlelek/Raneto#171]
I have used alot of acronyms within my filenames and they are converted to titlecase within the application.

Such as SEO => Seo

Doesn't really work, is there a way to keep the acronyms as capitalized words?

**Comment by ryanlelek** [comment]
Hi Ben,

Yes, there is now functionality for this. Not sure when it was added.
Simply add a "Title" to the metadata section at the top of the file
```
Title: SEO With Correct CAPITALS
```

Closing this issue, but please open a new one if you have further questions or suggestions



Full Page Example
```
/*
Title: SEO Delete Pages
Sort: 3
*/

Deleting pages in Raneto is as simple as deleting the Markdown file (`.md`) from the content folder.
```
