### ISSUE TITLE
Path to v1.0.0

### ISSUE THREAD

**Issue by ryanlelek** [ryanlelek/Raneto#185]
Raneto has gotten a lot of adoption and support, with a community adding lots of great improvements. There has been some confusion around how to enable some features as well as how everything interacts together with the settings file. So, before we release v1.0.0, let's give the repo and docs a good look-through and refine it.

v0.13.0 will be the final release for feature additions and then focus will shift to releasing v1.0.0 by clarifying what we have in our code, documentation, and increasing support for multiple platforms (Linux, Windows, OS X)

You're welcome to submit new feature updates but they will be included and merged after v1.0.0 releases or on a separate branch.

Ryan

**Comment by mohammadrafigh** [comment]
@ryanlelek I may be able to do some UI improvements (only by changing html, css files). Is this considered as new feature or can we include this in v.1.0.0?

**Comment by ryanlelek** [comment]
That'd be great @mohammadrafigh, any improvements to UI would be accepted.

I would also appreciate help upgrading to the latest jQuery version (v2.x to v3.x). Mainly want to ensure everything is working correctly in the UI instead of just upgrading and hoping for the best

**Comment by mohammadrafigh** [comment]
@ryanlelek ok I'm going for it. I have 2-3 free days from now I will work on these UI things.

**Comment by ryanlelek** [comment]
Thanks @mohammadrafigh , every bit, big or small, helps and is appreciated!

**Comment by ryanlelek** [comment]
This is being replaced by #374 
Closing
