### ISSUE TITLE
npm update in post-install breaks shrinkwrap

### ISSUE THREAD

**Issue by rayder441** [ryanlelek/Raneto#195]
There is a call to `npm update` in the post-install hook:
```(javascript)
"scripts": {
    "postinstall": "npm update && npm run gulp",
```
This causes the well-known ["extraneous deps" error](https://github.com/thewoolleyman/npm-shrinkwrap-helper) when running `npm shrinkwrap`.

(BTW, thanks for this great package!)

**Comment by ryanlelek** [comment]
Thank you for submitting and fixing.
Closing
