### ISSUE TITLE
Apostrophes (') in search don't work

### ISSUE THREAD

**Issue by quackenbush** [ryanlelek/Raneto#215]
Adding an apostrophe in the search seems to break it and give no results:

OK: "sorting i am" => many results
http://docs.raneto.com/?search=sorting+i+am

Bad: "sorting i'm" => zero results
http://docs.raneto.com/?search=sorting+i'm

**Comment by ryanlelek** [comment]
Just tested and this seems to be resolved.
Thanks to @cassiobock for the improvements

Closing.
