### ISSUE TITLE
How to hide folders in content from the home page?

### ISSUE THREAD

**Issue by nmMmnmMmn** [ryanlelek/Raneto#225]
How should I do to hide folders and/or any md page from the home page, please?
I can't find any information about hide pages or folders in demo site. Did I miss something?

Thanks!

**Comment by apepelis** [comment]
I'm having this same issue. 
is it this:
https://github.com/gilbitron/Raneto/issues/55

**Comment by ryanlelek** [comment]
Hi there,

Good news, this has been added.
You can hide directories and files on the 

First, make sure you're on the latest version of Raneto.
Then, see the following pages:
- [Category Meta](https://github.com/ryanlelek/Raneto/blob/5ae78ba2c00773226cde7190e008445266e90418/example/content/usage/category-meta.md)
- [Page Meta](https://github.com/ryanlelek/Raneto/blob/5ae78ba2c00773226cde7190e008445266e90418/example/content/usage/page-meta.md)
- [Category Example](https://github.com/ryanlelek/Raneto/blob/5ae78ba2c00773226cde7190e008445266e90418/test/content/sub/not_on_home/meta)
- [Page Example](https://github.com/ryanlelek/Raneto/blob/5ae78ba2c00773226cde7190e008445266e90418/test/content/hidden-page.md)

Note: This will only hide the pages on the home page and they will still be accessible if someone types in the URI
