### ISSUE TITLE
Support non-latin characters (i.e Arabic)

### ISSUE THREAD

**Issue by AhmadIbrahiim** [ryanlelek/Raneto#244]
Greeting ,

Since [#Raneto ](https://github.com/gilbitron/Raneto) , [#Lunr ](https://github.com/olivernn/lunr.js)  does not support the non-latien characters could you please refer me to a solution where do i can add Arabic to the supported languages . 
Thanks.

**Comment by ryanlelek** [comment]
Hello @AhmadIbrahiim 

You are right.
Raneto's RTL support for languages like Arabic needs improvement.
The upgrade to Bootstrap v5.x should fix RTL support.
After testing, it's able to save and display Arabic characters.
Once RTL is fixed, it should work ok.
We'd need your help to test.

I'm not aware of any other projects like Raneto that would support it.
If you're ok setting up MediaWiki (what powers Wikipedia), it's a widely-supported product that probably handles many languages well.
