### ISSUE TITLE
Error with start

### ISSUE THREAD

**Issue by jimmyr57000** [ryanlelek/Raneto#245]
Hello 

i have this error :( https://prnt.sc/i51uu7

Thanks you !

**Comment by jimmy-rich** [comment]
Log: http://prntscr.com/i5ibqc

**Comment by Orhideous** [comment]
@jimmy-rich Upgrade your node to 4.x or higher. Before this uninstall system-provided nodejs.
See: https://nodejs.org/en/download/package-manager/

**Comment by jimmy-rich** [comment]
Hello,

Thansks you @Orhideous 

I have other problem :( -> Cannot POST /login

Auth: true
Password set..

Thanks you

**Comment by Orhideous** [comment]
@jimmy-rich Please, provide some error logs or so.

**Comment by ryanlelek** [comment]
Thanks for assisting @Orhideous 
@jimmyr57000 please install the latest version of Node.js and Raneto
Unfortunately, your screenshots are no longer loading for me when I visited.

Please open a new issue if you're still experiencing problems or have questions
