### ISSUE TITLE
Nodejs 10 cousing error in deployment

### ISSUE THREAD

**Issue by h3ndro** [ryanlelek/Raneto#260]
hi, recently nodejs is updated to nodejs 10, apparently it made raneto deployment failed. Below is a build log from heroku:
`-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  >=4.0.0
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >=4.0.0...
       Downloading and installing node 10.0.0...
       Using default npm version: 5.6.0
-----> Restoring cache
       Skipping cache restore (new-signature)
-----> Building dependencies
       Installing node modules (package.json + package-lock)
       
       > raneto@0.14.0 postinstall /tmp/build_b42fc9985ce4a09b4e013f50fb3ae2c6
       > npm run gulp
       
       
       > raneto@0.14.0 gulp /tmp/build_b42fc9985ce4a09b4e013f50fb3ae2c6
       > gulp
       
       gulp[227]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
       1: node::Abort() [gulp]
       2: 0x87b6c5 [gulp]
       3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
       4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [gulp]
       5: 0xad5b9f [gulp]
       6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
       7: 0x381c2600427d
       Aborted
       npm ERR! code ELIFECYCLE
       npm ERR! errno 134
       npm ERR! raneto@0.14.0 gulp: `gulp`
       npm ERR! Exit status 134
       npm ERR!
       npm ERR! Failed at the raneto@0.14.0 gulp script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.q2hwY/_logs/2018-04-25T07_34_14_347Z-debug.log
       npm ERR! code ELIFECYCLE
       npm ERR! errno 134
       npm ERR! raneto@0.14.0 postinstall: `npm run gulp`
       npm ERR! Exit status 134
       npm ERR!
       npm ERR! Failed at the raneto@0.14.0 postinstall script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.q2hwY/_logs/2018-04-25T07_34_14_387Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed`

just restrict raneto to use nodejs 9.11.1 and deployment success

**Comment by TheGabrielRS** [comment]
it's only a change of version or a fresh install?

it seems like a bug with some dependency or even the package-lock.json like referenced on the gulp repository https://github.com/gulpjs/gulp/issues/2162

**Comment by philipstratford** [comment]
Thanks for the link, @TheGabrielRS. [This answer](https://github.com/gulpjs/gulp/issues/2162#issuecomment-384506747) from that thread fixed it for me. After the unsuccessful Raneto install I deleted the _node_modules_ folder and the _package-lock.json_ files then ran `npm install --unsafe-perm=true` and Raneto installed successfully.

**Comment by ryanlelek** [comment]
Yep, error message was definitely related to `gulp`
Glad you figured it out with @TheGabrielRS 's suggestion.

This might be solved in the latest versions of Node, Gulp, etc. (depends on your OS)

Closing, but please open a new issue if this happens again.
I'll mark this for when we update our documentation so we can clarify for others.
