### ISSUE TITLE
Can't install on os x

### ISSUE THREAD

**Issue by intmainreturn00** [ryanlelek/Raneto#275]
MBP-andrey-2:raneto owl$ cd Raneto
MBP-andrey-2:Raneto owl$ npm install

> fsevents@1.1.3 install /Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from In file included from ../fsevents.cc../fsevents.cc::8585:
:
../src/methods.cc../src/methods.cc::1414::1212::  warningwarning: : 'Call''Call'  isis  deprecateddeprecated  [-Wdeprecated-declarations][-Wdeprecated-declarations]

  handler->Call(3, argv);  handler->Call(3, argv);

           ^           ^

../../nan/nan.h../../nan/nan.h::16171617::33::  notenote: : 'Call''Call'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

  NAN_DEPRECATED inline v8::Local<v8::Value>  NAN_DEPRECATED inline v8::Local<v8::Value>

  ^
  ^
../../nan/nan.h:98:40: ../../nan/nan.h:note98: :expanded 40from: macro  'NAN_DEPRECATED'
note: expanded from macro 'NAN_DEPRECATED'# define NAN_DEPRECATED __attribute__((deprecated))

                                       ^
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
1 warning generated.
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR!   SOLINK_MODULE(target) Release/fse.node
build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.9.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.9.0/bin/node" "/Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/10.9.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
  COPY /Users/owl/imperial-lab/raneto/Raneto/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> raneto@0.16.0 postinstall /Users/owl/imperial-lab/raneto/Raneto
> npm run gulp

> raneto@0.16.0 gulp /Users/owl/imperial-lab/raneto/Raneto
> gulp

gulp[47011]: ../src/node_contextify.cc:627:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x10003818c node::Abort() [/usr/local/bin/node]
 2: 0x100037367 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: 0x10005c3de node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x1001f14e8 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x1001f0811 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x1001f0270 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x258a9b35c01d 
 8: 0x258a9b30d145 
 9: 0x258a9b38b900 
10: 0x258a9b3118b5 
11: 0x258a9b3118b5 
Abort trap: 6

**Comment by tigrin76** [comment]
I got it working on OSX but logged in as SU before installing. Don't have to stay in SU to use, but install was successful per documentation.

**Comment by dkbnguyen** [comment]
You can try removing existing `node_modules/` and `package-json.lock` then `$ npm install` again.

**Comment by rgstephens** [comment]
I was not able to resolve this by solely removing `node_modules` and `package-json.lock`. Only when I did that and used `yarn` instead of npm was I able to resolve the issue.

My Dockerfile now has these commands:

```
RUN test -e node_modules || rm -rf node_modules
RUN test -e package-json.lock || rm -rf package-json.lock
RUN yarn global add gulp-cli pm2
...
RUN yarn
```

**Comment by ryanlelek** [comment]
Hi, I have not had any issues throughout the years on OS X / macOS.
Could you do the following steps to help me better understand the potential issue?
- Try cloning fresh and running your commands again
- What version of Node.js?
- Any logs in the process above.

This could indeed be the package-lock.json file using some weird platform specific compilation or binding/linking. Usually I delete this file and let it regen on each system in other projects. This could be why removing it along with the `node_modules/` directory solves the issue

**Comment by ryanlelek** [comment]
Lots of time has passed but it seems like this is more Node/OS related

We can add troubleshooting steps with the solutions you all mentioned
- Sometimes superuser needs to execute `npm install` because of NPM's installation directory
- Sometimes deleting `package-lock.json` and `node_modules/` or using yarn is a solution (Our command `make clean` deletes these files, but we should make that clear)

I'll mark this for update in the Documentation megathread (See link above).
Let's continue the discussion there. Closing this issue.
