### ISSUE TITLE
markdown & Latex

### ISSUE THREAD

**Issue by kongxiangyan** [ryanlelek/Raneto#283]
Hello, I want to know which markdown parser it use? And will it support Latex?

**Comment by ryanlelek** [comment]
Hi there,
Raneto uses "Marked" for its rendering
- [Marked Website](https://marked.js.org/)
- [Marked GitHub](https://github.com/markedjs/marked)

Currently there is no support for LaTeX.
Please join the discussion on #172 

Closing this issue
