### ISSUE TITLE
Use of glyphicon no longer in bootstrap 4.

### ISSUE THREAD

**Issue by GrahamDumpleton** [ryanlelek/Raneto#287]
The ``glyphicon-envelope`` is used for the "Still need help" contact email text, but bootstrap 4 doesn't include glyphicon now. Possibly use fontawesome instead.

**Comment by ryanlelek** [comment]
You're right. We'll add this to the list for Bootstrap 5 conversion

**Comment by ryanlelek** [comment]
Closing this to clean up.  
It lives on in the roadmap #374
