### ISSUE TITLE
Question: Implementation of update checking

### ISSUE THREAD

**Issue by ghost** [ryanlelek/Raneto#290]
Hey, I have question. I don't have too much time to analyze code base - I don't see this but maybe it is there.
Is there implementation of checking for updates? Like you use
```
yum/apt update
```
And it shows that **Raneto** have update?

**Comment by vipul1298** [comment]
i think 
yum check-update  will work for checking updates

**Comment by ryanlelek** [comment]
Hi, yes. Thanks for asking.
Run `npm outdated` from your project's root (where the `package.json` file is).

Closing this...
Adding to documentation issue so we can provide clearer instructions
