### ISSUE TITLE
Error: Whoops. Looks like this page doesn't exist

### ISSUE THREAD

**Issue by xhj967** [ryanlelek/Raneto#293]
![qq 20190226102059](https://user-images.githubusercontent.com/46950578/53382787-4cfa2500-39b0-11e9-87be-5f8c39f1bd14.jpg)

Thanks!

**Comment by xhj967** [comment]
![qq 20190226102414](https://user-images.githubusercontent.com/46950578/53382913-c0039b80-39b0-11e9-92e4-e18121346171.png)

and the page show strangely, not at the right space, but at the bottom;

**Comment by xhj967** [comment]
![qq 20190226104756](https://user-images.githubusercontent.com/46950578/53384178-f80cdd80-39b4-11e9-9301-93e6bfc00d7a.png)

**Comment by benruehl** [comment]
Same for me. Just downloaded the latest release (v0.16.2) and entered `npm install` and `npm run start_win` into Powershell (on Windows).
Looking at the error messages I would guess that a directory called `lib` is missing in  `themes\default\public`.

![image](https://user-images.githubusercontent.com/17962788/55788714-23591100-5ab9-11e9-9d38-3f30f911ad12.png)

**Comment by benruehl** [comment]
Ok I solved it now. Before running `npm run start_win` one has to run `npm run gulp` first. The gulp script copies some depedencies to the lib folder.

In my opinion, as this is not documented at [http://docs.raneto.com/install/installing-raneto](http://docs.raneto.com/install/installing-raneto) it should be either added to the docs or the gulp task should be included in the `start_win` command.

**Comment by eloekset** [comment]
How did you start off, @benruehl?

The docs tell me to run `git init` in my empty project directory, but obviously that's not all that is needed. The prerequisites list tells me to install node, so I ran `npm init` also, and then added renato by running `npm install renato`. 

After some browsing in the **node_modules/renato/** folder, I started copying folders from the **themes** folder, but still that's not all that is needed.

I think the documentation lacks some prerequisites. Is a node express app supposed to be the startoff point?

**Comment by benruehl** [comment]
@eloekset I followed the steps explained here: [http://docs.raneto.com/install/installing-raneto](http://docs.raneto.com/install/installing-raneto)
Step 2 gives you the option to add Raneto as a dependency or include the source files of Raneto directly. I did the latter.

**Comment by ryanlelek** [comment]
Yes, our docs need work.

Here's my summary, if I'm understanding correctly.
There are files generated in this repo that populate `public/lib`
That population tools is called `gulp`
If `gulp` was not run (maybe Windows didnt run it, maybe it's not run when included as a module), those files would not exist.

Actions we'll take:
- Update documentation
- Potentially include the pre-generated public directory
- Potentially hook into post-build scripts within NPM when used as a module
- Potentially split off examples into their own repositories and use Raneto more as a library.

This is late, but if you're still having problems or questions, please ask them here

**Comment by ryanlelek** [comment]
Closing and moving to documentation megathread (see above)
