### ISSUE TITLE
IIS installation

### ISSUE THREAD

**Issue by joaorsfonseca** [ryanlelek/Raneto#295]
Is it possible to deploy Raneto to an IIS server? if so, how can i do it?
Thanks.

**Comment by TheGabrielRS** [comment]
yes you can!

any OS that runs NodeJS can, as far as I know the navigation filesystem is fullcompatible with Windows and Unix systems 😄 

it's just a matter of configuring the IIS server with the right dependencies and tweaks for the language

**Comment by philipstratford** [comment]
As long as you configure Raneto to run on a different port to IIS the two can run side-by-side quite nicely. I wrote a little tutorial based on my experience of setting up Raneto to run under a Windows Service and it's quite happy on the same box as IIS: https://collection.code.blog/2018/12/01/running-raneto-as-a-windows-service/

**Comment by joaorsfonseca** [comment]
Thanks both for your anwsers..

The question is that i have limited access to the server. I can only access the iis window. I was expecting to have de possibility to somehow build a package and then deploy it. 

Is it possible? I've looked into webpack but so far without any luck :(

**Comment by philipstratford** [comment]
It is possible to run node.js applications in IIS (see https://github.com/Azure/iisnode, for example), but without access to configure the server beyond just IIS I don't think you're going to have much joy, unfortunately.

**Comment by joaorsfonseca** [comment]
Well. At least on my machine i can proceed with it :)
Also, the final version will be published on Azure, so if iisnode already runs on Azure I think there is no problem there.

But looking at iisnode, i'm a little bit stuck on how to build it or use it..

**Comment by ryanlelek** [comment]
Thank you for the discussion, I'll mark this as "add-to-docs" for inclusion in the Raneto guides on how to host on Windows/IIS.

**Comment by ryanlelek** [comment]
Closing to clean up and moving to megathread for documentation update (see above).

Would any of you be able to assist in testing? I do not have IIS experience.
If you're available to help, just comment here and re-open. Thanks
