### ISSUE TITLE
Actions button is displayed even if not logged in

### ISSUE THREAD

**Issue by ybizeul** [ryanlelek/Raneto#297]
The _Actions_ button is displayed on a content, even though the use isn't logged in.

If you pick _Edit_ in the menu, nothing happens because the Panel isn't displayed by the template.

The button shouldn't be displayed at all

**Comment by ryanlelek** [comment]
Thanks for reporting.
I tested the latest release and now things appear to be working.
Only the "login" button is displayed on the home page and on the page itself

Closing
