### ISSUE TITLE
Colons cannot be used in page title

### ISSUE THREAD

**Issue by benruehl** [ryanlelek/Raneto#298]
Unfortunately, colons cannot be used as part of a page's title in the meta section.

For example the following

```
/*
Title: Knowledge: Introduction to my tool
*/
```

should give the title 'Knowledge: Introduction to my tool' but instead produces only 'Knowledge'.
I am using version 0.16.2.

**Comment by endo64** [comment]
Did you try with %3A? Didn't test but it might work.

**Comment by benruehl** [comment]
Nope, does not work unfortunately. It simply results in 'Knowledge%3A Introduction to my tool'.

**Comment by benruehl** [comment]
By looking at the projects unit tests I found out that one can use yaml syntax to declare page metadata.

So instead of

```
/*
Title: Knowledge: Introduction to my tool
*/
```

one can write

```yaml
---
Title: "Knowledge: Introduction to my tool"
---
```

which results in the expected output.
I missed that at first because this feature is not mentioned in the [docs](http://docs.raneto.com/usage/creating-pages).

**Comment by endo64** [comment]
Thanks for noting this. If you edit meta data via the web UI it uses this format.

**Comment by ryanlelek** [comment]
Thanks for reporting.
Closing this and adding to the megathread of Documentation updates (see above)
