### ISSUE TITLE
upload local image

### ISSUE THREAD

**Issue by chenfengrugao** [ryanlelek/Raneto#300]
markdown files are in examples directory while images are in themes/default/public/images/，so is there a good way to manage the local images? 
I deployed Raneto as a small team knowledge share website. And write markdown articles in local and push them to examples directory by git.  It will be better if the local images are store in the same directory as the markdown files. Or else, I must write a copy script to public/images/.

**Comment by chenfengrugao** [comment]
I made a symbol link public/image to examples/image. Looks petty good.

**Comment by ryanlelek** [comment]
Thank you for sharing!

**Comment by ryanlelek** [comment]
Closing this to cleanup.
Adding this to Roadmap for v0.19 (see above)
