### ISSUE TITLE
npm run gulp does not copy libs to public/gulp

### ISSUE THREAD

**Issue by jrichardsz** [ryanlelek/Raneto#332]
Execution of `npm run gulp`  does not show errors but files are not copied. I'm using node 10 and ubuntu

If Raneto wants to be used as npm library, instead the requirement of clone the entire source code, maybe to provide the required js files **public/lib** as part of release could be an option.

Gulp would be for **upgrade** these libraries like bootstrap, swwetalert, etc

**Comment by ryanlelek** [comment]
You are right.
This will be completed during the separation of the example into its own repo #296

After the separation is completed, we should be left with a good example that uses Raneto as a library and has the static assets generated.

Closing this issue to cleanup.
We'd love to have your thoughts on the upcoming Roadmap (see pinned issue at top of Issues page)
