### ISSUE TITLE
Easy way to set up permanent redirects to a new url?

### ISSUE THREAD

**Issue by ArtFlag** [ryanlelek/Raneto#349]
Hi, 

I'm trying to set up a mapping for each page to redirect the user to a new page that has a different base url. 
What's the most straight forward to achieve this?

For technical reasons, I have to do this from Raneto. Any suggestions?

Thanks!

**Comment by ArtFlag** [comment]
Thanks for the quick reply! 
I'm just wondering if I can edit the hostname with this bit? This looks like this would only change the location, for example:
`https://example.com/mydocs/mypage` -> `https://example.com/somenewdocs/mynewpage` instead of `https://acme.com/somepath/mypage` ?

**Comment by ryanlelek** [comment]
You are correct, the hostname would not change.
Updated snippet:
```
app.get('/old/*', function (req, res, next) {
    var new_path = req.originalUrl.replace('/old/', '/new/');
    res.redirect(302, 'https://www.nedomain.com' + new_path);
});
```

This is a good feature request though.
It's likely to be needed occasionally.
One solution is the above, but on an individual level can be done with YAML metadata in the page to redirect.

Including this in Roadmap for v0.19 (Nice to have)

**Comment by ryanlelek** [comment]
Closing and moving to Roadmap v0.19 (see above).
Please move discussion there
