### ISSUE TITLE
Raneto-0.17.0 start fail

### ISSUE THREAD

**Issue by NeverDieSuddenly** [ryanlelek/Raneto#360]
C:\Users\????\Desktop\Raneto-0.17.0\node_modules>npm start

> raneto@0.17.0 start C:\Users\????\Desktop\Raneto-0.17.0
> DEBUG=raneto node example/server.js

'DEBUG' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raneto@0.17.0 start: `DEBUG=raneto node example/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raneto@0.17.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\????\AppData\Roaming\npm-cache\_logs\2021-10-15T08_21_27_470Z-debug.log

**Comment by hushitong** [comment]
一个办法，修改package.json文件
把`"start": "DEBUG=raneto node example/server.js"`修改为`"start": "node example/server.js"`
然后还是`npm start`运行就不会报错

**Comment by ryanlelek** [comment]
As hushitong mentioned, please change this line in `package.json`:
`"start": "DEBUG=raneto node example/server.js"`
to
`"start": "node example/server.js"`

It looks like your current working directory is `node_modules`
`C:\Users????\Desktop\Raneto-0.17.0\node_modules>npm start`
Make sure you're in the project root.
`C:\Users????\Desktop\Raneto-0.17.0`

(Note: I used online translator to understand request, which may not be accurate)
