### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by J-GainSec** [ryanlelek/Raneto#368]
Hi, I found three security issues within your application. I'm hoping to get in touch to disclose further details about them. If you can reach out via GitHub or security@gainsecmail.com I will share the details privately. 

Thank you for your time

**Comment by ryanlelek** [comment]
Thank you, emailed
cc @gilbitron

**Comment by ryanlelek** [comment]
Should be fixed in Release v0.17.1
Thank you for reporting

**Comment by ryanlelek** [comment]
@J-GainSec Hi there.
I see the CVEs flowing into the automated reporting systems.
Were you able to re-test v0.17.1 with patches? (If not that's ok)

Anything else you need or can we close this issue?

**Comment by J-GainSec** [comment]
I have not but I'm happy too in the upcoming week if you'd like. 

I'm all good if not. You can close the issue.

Thank you for your responsiveness and professionalism.
