### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by Et43** [ryanlelek/Raneto#400]
Create a security policy for this repository, to enable people to submit potential security vulnerabilities in a secure manner to allow for a proper triage and responsible disclose process to take place.

You can do this simply by going to the security tab for the repo.

**Comment by ryanlelek** [comment]
Added in commit https://github.com/ryanlelek/Raneto/commit/4717a90dec94c71d7b4cdcdaec606d26a4ca55ff

Do you have vulns to disclose?

**Comment by Et43** [comment]
Yes I have a vuln to disclose.

**Comment by ryanlelek** [comment]
File added and report received (long ago).
Thank you!

Closing
