### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by ryanlelek** [ryanlelek/Raneto#76]
- config.js moved to example/ (since Raneto is now NPM-installable)
- The ./bin directory is no longer needed
- Heroku deployment tutorial update, to show the new NPM usage of Raneto

**Comment by rdbrdd** [comment]
I am not sure if the documentation needs an update or what but I cannot get heroku to work right following the directions.

**Comment by ryanlelek** [comment]
Ok, updating now

**Comment by ryanlelek** [comment]
@rdbrdd , Updated. Please let me know here if you have any more issues.

http://docs.raneto.com/tutorials/deploying-raneto-to-heroku

**Comment by rdbrdd** [comment]
The new directions worked.  It seems like the issue was the inclusion of the "Procfile" that was causing it to fail for me.  Thank you.

**Comment by ryanlelek** [comment]
Awesome, great to hear!
Yes, you're right. The Procfile had an outdated script in it that we forgot to update.

We'll look through the documentation and update it, and move most of the ReadMe contents to the Raneto docs to prevent split-brain from happening again.

Let us know how else we can be helpful

**Comment by stickgrinder** [comment]
Sorry, I may miss some basics in node and npm usage but how am I supposed to make Raneto start from a directory other than example? Should I upgrade `package.js` file?

the example dir Is hardcoded in `bin/raneto` exectuable also.
I admit I am confused!

**Comment by mohammadrafigh** [comment]
yes you should update `package.json` and change the lines 27 and 28 regarding to your needs.

**Comment by ryanlelek** [comment]
The repo is currently confusing, so it's not something you're missing.
I'll dedicate time this weekend to cleaning things up and get it started back on track

In the meantime, you may find this repository helpful to deploy (Ubuntu v14.04 only, DigitalOcean recommended)

@stickgrinder @mohammadrafigh Please contact me directly in the meantime if you have pressing issues. Email address is in profile

**Comment by ryanlelek** [comment]
Forgot the repo. here it is
https://github.com/ryanlelek/raneto-devops

**Comment by ryanlelek** [comment]
Linking this to the megathread of Documentation updates and the Roadmap.
Please see above links.

Closing this issue.
Join us in the discussion on the Roadmap/Docs or re-open this issue with questions
